# Generated by Django 4.1.1 on 2022-09-10 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_company_name', models.CharField(max_length=200, null=True)),
                ('First_company_desg', models.CharField(max_length=200, null=True)),
                ('First_company_duration', models.CharField(max_length=200, null=True)),
                ('First_company_sal', models.CharField(max_length=200, null=True)),
                ('Second_company_name', models.CharField(max_length=200, null=True)),
                ('Second_company_desg', models.CharField(max_length=200, null=True)),
                ('Second_company_duration', models.CharField(max_length=200, null=True)),
                ('Second_company_sal', models.CharField(max_length=200, null=True)),
                ('Third_company_name', models.CharField(max_length=200, null=True)),
                ('Third_company_desg', models.CharField(max_length=200, null=True)),
                ('Third_company_duration', models.CharField(max_length=200, null=True)),
                ('Third_company_sal', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empexperience',
            },
        ),
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pg_course', models.CharField(max_length=200, null=True)),
                ('pg_clg', models.CharField(max_length=200, null=True)),
                ('pg_year_of_passing', models.CharField(max_length=20, null=True)),
                ('pg_percentage', models.CharField(max_length=20, null=True)),
                ('graduation', models.CharField(max_length=200, null=True)),
                ('graduation_clg', models.CharField(max_length=200, null=True)),
                ('graduation_year_of_passing', models.CharField(max_length=20, null=True)),
                ('graduation_percentage', models.CharField(max_length=20, null=True)),
                ('hsc', models.CharField(max_length=200, null=True)),
                ('hsc_clg', models.CharField(max_length=200, null=True)),
                ('hsc_year_of_passing', models.CharField(max_length=20, null=True)),
                ('hsc_percentage', models.CharField(max_length=20, null=True)),
                ('ssc', models.CharField(max_length=200, null=True)),
                ('ssc_school', models.CharField(max_length=200, null=True)),
                ('ssc_year_of_passing', models.CharField(max_length=20, null=True)),
                ('ssc_percentage', models.CharField(max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'empeducation',
            },
        ),
    ]
